export const NOTIFICATION_MAP = {
	guard_absent: "Guard Absent",
	proximity_alert: "Proximity Alert",
	late_checkin: "Late Check-In",
	early_departure: "Early Departure",
	return_onsite: "Return On-Site",
	untracked_logout: "Untracked Logout",
	reconnected_onsite: "Reconnected On-Site",
	assigned_hours_discrepancy: "Assigned Hours Discrepancy",
	worked_hours_discrepancy: "Worked Hours Discrepancy",
	schedule_published: "Schedule Published",
	schedule_unconfirmed: "Schedule Unconfirmed",
	schedule_rejection: "Schedule Rejection",
	schedule_accepted: "Schedule Accepted",
	enroute_confirmation: "Enroute Confirmation",
	enroute_unconfirmed: "Enroute Unconfirmed",
	enroute_rejected: "Enroute Rejected",
};
